
-- ============================================================
-- MURMUR ANALYTICS — SNOWFLAKE SETUP
-- ============================================================

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS DEV_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE;

-- Resource monitor
CREATE RESOURCE MONITOR IF NOT EXISTS MURMUR_MONITOR
    WITH CREDIT_QUOTA = 20
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 95 PERCENT DO SUSPEND;

ALTER WAREHOUSE DEV_WH SET RESOURCE_MONITOR = MURMUR_MONITOR;

-- Database and schemas
CREATE DATABASE IF NOT EXISTS MURMUR_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS MURMUR_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS MURMUR_ANALYTICS.STAGING;
CREATE SCHEMA IF NOT EXISTS MURMUR_ANALYTICS.MARTS;

-- Roles
CREATE ROLE IF NOT EXISTS MURMUR_LOADER;
CREATE ROLE IF NOT EXISTS MURMUR_TRANSFORM;

-- Warehouse access
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE MURMUR_LOADER;
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE MURMUR_TRANSFORM;

-- MURMUR_LOADER — owns raw schema
GRANT USAGE ON DATABASE MURMUR_ANALYTICS TO ROLE MURMUR_LOADER;
GRANT USAGE ON SCHEMA MURMUR_ANALYTICS.RAW TO ROLE MURMUR_LOADER;
GRANT CREATE TABLE ON SCHEMA MURMUR_ANALYTICS.RAW TO ROLE MURMUR_LOADER;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA MURMUR_ANALYTICS.RAW TO ROLE MURMUR_LOADER;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA MURMUR_ANALYTICS.RAW TO ROLE MURMUR_LOADER;

-- MURMUR_TRANSFORM — reads raw, owns staging and marts
GRANT USAGE ON DATABASE MURMUR_ANALYTICS TO ROLE MURMUR_TRANSFORM;
GRANT USAGE ON SCHEMA MURMUR_ANALYTICS.RAW TO ROLE MURMUR_TRANSFORM;
GRANT SELECT ON ALL TABLES IN SCHEMA MURMUR_ANALYTICS.RAW TO ROLE MURMUR_TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MURMUR_ANALYTICS.RAW TO ROLE MURMUR_TRANSFORM;
GRANT USAGE ON SCHEMA MURMUR_ANALYTICS.STAGING TO ROLE MURMUR_TRANSFORM;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA MURMUR_ANALYTICS.STAGING TO ROLE MURMUR_TRANSFORM;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA MURMUR_ANALYTICS.STAGING TO ROLE MURMUR_TRANSFORM;
GRANT USAGE ON SCHEMA MURMUR_ANALYTICS.MARTS TO ROLE MURMUR_TRANSFORM;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA MURMUR_ANALYTICS.MARTS TO ROLE MURMUR_TRANSFORM;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA MURMUR_ANALYTICS.MARTS TO ROLE MURMUR_TRANSFORM;

-- Assign roles to your user
GRANT ROLE MURMUR_LOADER TO USER bubchampagne;
GRANT ROLE MURMUR_TRANSFORM TO USER bubchampagne;